name: Prepare release

on:
  pull_request:
    types:
      - closed  # Trigger only when the pull request is merged
    branches:
      - feat/release-ci

jobs:
  update-version-and-changelog:
    if: github.event.pull_request.merged == true  # Run only if the PR was merged
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Gradle task to update version and changelog
        run: ./gradlew updateVersionAndChangelog -Pversion="${{ github.event.pull_request.title }}" -PchangelogText="${{ github.event.pull_request.body }}"

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Commit and push changes
        run: |
          git add CHANGELOG.md
          git add agentseek/build.gradle.kts
          git commit -m "Updated CHANGELOG.md and build.gradle.kts for new release"
          git push origin HEAD:${{ github.head_ref }}  # Push to the branch that opened the PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}