name: Build and Release

on:
  push:
    branches:
      - build/ci

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Extract version from build.gradle.kts
        id: get_version
        run: |
          cd agentseek
          VERSION=$(grep "^version" build.gradle.kts | sed -E 's/^version = "(.*)"/\1/')
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Extract changelog for the version
        id: get_changelog
        run: |
          # Extract the changelog for the specific version
          VERSION="${{ env.version }}"
          sed -n "/^## \\[${VERSION}\\]/,/^## \\[/p" CHANGELOG.md | sed '$d' > CHANGELOG_OUTPUT.md
          echo "changelog<<EOF" >> $GITHUB_ENV
          cat CHANGELOG_OUTPUT.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Build fat JAR for agentseek
        run: |
          ./gradlew clean :agentseek:shadowJar # Assumes usage of the Shadow plugin for fat JARs
        env:
          GRADLE_USER_HOME: ${{ runner.temp }}/.gradle # Avoid Gradle daemon issues in GitHub Actions

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: "v${{ env.version }}"
          release_name: "Release ${{ env.version }}"
          body: "${{ steps.get_changelog.outputs.changelog }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload fat JAR
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: agentseek/build/libs/agentseek-${{ env.version }}-all.jar
          asset_name: agentseek-fat-${{ env.version }}.jar
          asset_content_type: application/java-archive